- name: Download and install kind
  get_url:
    url: "https://kind.sigs.k8s.io/dl/{{ kind_version }}/kind-linux-amd64"
    dest: /usr/local/bin/kind
    mode: '0755'
    checksum: "sha256:{{ kind_hash }}"
